-- SQL Retail Sales Analysis
CREATE DATABASE sql_project_p1;

-- create table
DROP TABLE IF EXISTS retail_sales;
CREATE TABLE retail_sales
     (
     transactions_id INT PRIMARY KEY,
	 sale_date DATE,
	 sale_time TIME,
	 customer_id INT,
	 gender VARCHAR(15),
	 age INT,
	 category VARCHAR(15),
	 quantiy INT,
	 price_per_unit FLOAT,
	 cogs FLOAT,
	 total_sale FLOAT
	 );

SELECT * FROM retail_sales

select count(*) from retail_sales

-- Cleaning data

--checking null values
SELECT * FROM retail_sales 
WHERE 
     transactions_id IS NULL
	 OR
	 sale_date IS NULL
	 OR
	 sale_time IS NULL
	 OR
	 customer_id IS NULL
	 OR
     age IS NULL
	 OR
	 category IS NULL
	 OR
	 quantiy IS NULL
	 OR
	 price_per_unit IS NULL
	 OR
	 cogs IS NULL
	 OR
	 total_sale IS NULL;

-- deleting null values
DELETE FROM retail_sales 
WHERE 
     transactions_id IS NULL
	 OR
	 sale_date IS NULL
	 OR
	 sale_time IS NULL
	 OR
	 customer_id IS NULL
	 OR
     age IS NULL
	 OR
	 category IS NULL
	 OR
	 quantiy IS NULL
	 OR
	 price_per_unit IS NULL
	 OR
	 cogs IS NULL
	 OR
	 total_sale IS NULL;

--data exploration

--how many sales we have ?
SELECT COUNT(*) as total_sales FROM retail_sales

--how many unique customer we have?
SELECT COUNT(DISTINCT customer_id) as Total_Customer FROM retail_sales

--how many categories we have?
SELECT DISTINCT category as total_categories FROM retail_sales


--Data Analysis and Business problems

--1.What is the total revenue generated by each product category?
SELECT category,
       SUM(quantiy * price_per_unit) AS total_revenue
FROM retail_sales
GROUP BY category
ORDER BY total_revenue DESC;


--2.Which month generated the highest revenue?
SELECT 
   DATE_TRUNC('month',sale_date) AS month,
   SUM(quantiy * price_per_unit) as total_revenue
   FROM retail_sales
   GROUP BY month
   ORDER BY total_revenue DESC
   LIMIT 1


--3.What is the average revenue per transaction?
SELECT 
   AVG(quantiy*price_per_unit) AS avg_revenue_per_transaction
FROM retail_sales


--4.Do males or females spend more on average?
SELECT 
    gender,
    AVG(quantity * price_per_unit) AS avg_spending
FROM retail_sales
GROUP BY gender
ORDER BY avg_spending DESC;



--5.What is the average order value by gender?
SELECT 
    gender,
    AVG(quantity * price_per_unit) AS avg_order_value
FROM retail_sales
GROUP BY gender;


--6.Who are the top 10 highest spending customers?
SELECT 
    customer_id,
    SUM(quantity * price_per_unit) AS total_spent
FROM retail_sales
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;


--7.At what hour of the day do we see peak sales?
SELECT 
    EXTRACT(HOUR FROM sale_time) AS hour,
    SUM(quantity * price_per_unit) AS total_revenue
FROM retail_sales
GROUP BY hour
ORDER BY total_revenue DESC
LIMIT 1;



--8.Are morning sales higher than evening sales?
SELECT 
    CASE 
        WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 6 AND 11 THEN 'Morning'
        WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
        WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 18 AND 23 THEN 'Evening'
        ELSE 'Night'
    END AS time_period,
    SUM(quantity * price_per_unit) AS total_revenue
FROM retail_sales
GROUP BY time_period
ORDER BY total_revenue DESC;



--9.Which day of the week has the highest revenue?
SELECT 
    TO_CHAR(sale_date, 'Day') AS day_of_week,
    SUM(quantity * price_per_unit) AS total_revenue
FROM retail_sales
GROUP BY day_of_week
ORDER BY total_revenue DESC
LIMIT 1;



--10.Is there seasonality in sales patterns? (Monthly Trend)
SELECT 
    DATE_TRUNC('month', sale_date) AS month,
    SUM(quantity * price_per_unit) AS total_revenue
FROM retail_sales
GROUP BY month
ORDER BY month;


--11.Which category sells the highest quantity?
SELECT 
    category,
    SUM(quantity) AS total_quantity
FROM retail_sales
GROUP BY category
ORDER BY total_quantity DESC
LIMIT 1;



--12.Which category has the highest revenue but lower quantity?
SELECT 
    category,
    SUM(quantity) AS total_quantity,
    SUM(quantity * price_per_unit) AS total_revenue
FROM retail_sales
GROUP BY category
ORDER BY total_revenue DESC;



--13.Are customers in certain age groups preferring specific categories?
SELECT 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 60 THEN '46-60'
        ELSE '60+'
    END AS age_group,
    category,
    SUM(quantity) AS total_quantity
FROM retail_sales
GROUP BY age_group, category
ORDER BY age_group, total_quantity DESC;


--14.What is the price sensitivity by category? (Average price & quantity)
SELECT 
    category,
    AVG(price_per_unit) AS avg_price,
    AVG(quantity) AS avg_quantity
FROM retail_sales
GROUP BY category
ORDER BY avg_price DESC;


--15.Customer Lifetime Value (Basic Version)
-- (Total revenue generated per customer)
SELECT 
    customer_id,
    SUM(quantity * price_per_unit) AS customer_lifetime_value
FROM retail_sales
GROUP BY customer_id
ORDER BY customer_lifetime_value DESC;



--16.Average Purchase Frequency per Customer
-- (Average number of transactions per customer)
SELECT 
    AVG(transaction_count) AS avg_purchase_frequency
FROM (
    SELECT 
        customer_id,
        COUNT(*) AS transaction_count
    FROM retail_sales
    GROUP BY customer_id
);



